### ISSUE TITLE
Handling POST redirects (301 vs 308?)

### ISSUE THREAD

**Issue by leftathome** [smiller171/go-redirect#19]
Not necessarily a big deal, but a client that's attempting a non-GET will follow a 301 redirect response with a GET to the new URL.

In order to tell the client that it should use the same method on the new redirected URL, the server would need to send a 308 response.

In more detail (includes fancy flowchart):
https://stackoverflow.com/questions/42136829/whats-difference-between-http-301-and-308-status-codes

Would you be amenable to adding a flag to support sending 308s for non-GET requests?

(If so I'd whip up a PR this weekend, otherwise it's no big deal, I'll just modify my URL monitors to avoid going through a redirect.)

**Comment by smiller171** [comment]
That would be great! I think it may be best to make 308 the new default (and do a major version bump). What are your thoughts on that?

**Comment by leftathome** [comment]
I was thinking of only returning a 308 if the request method wasn't GET.  Maybe put the whole thing behind a flag or environment variable.

**Comment by smiller171** [comment]
I lean towards allowing the user to select the redirect type with an envvar, with a default of 308 since it seems to be the best practice these days over 301. My only concern is change of behavior for existing users, which is why I'd do a major release.

**Comment by smiller171** [comment]
Perhaps a `STATUS_CODE` var that accepts any valid 300 code.

**Comment by smiller171** [comment]
@leftathome Is this something you still plan on working on or should I consider taking it on myself?

**Comment by leftathome** [comment]
I'm hoping to take a look at it after the next wave of migrations, most likely next weekend.

**Comment by leftathome** [comment]
I've submitted a PR that adds tests based on current behavior and I'm about to submit another one that modifies that behavior when the request isn't a GET.  The latter depends on the  former being merged first.

I'm following the codebase's lead on handling command line / environment parsing.  At the moment it doesn't seem to check environment variables at all...
